In [21]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.metrics import accuracy_score
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import roc_curve, roc_auc_score
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import log_loss

In [27]:
df = pd.read_csv("C:/Users/Administrator.DAI-PC2/Desktop/ML/Day1/Glass.csv")
le = LabelEncoder()
y = le.fit_transform(df["Type"])
X = df.drop("Type", axis = 1)

print(le.classes_)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state=2021, stratify=y)

gaussian = GaussianNB()
gaussian.fit(X_train, y_train)
y_pred = gaussian.predict(X_test)
y_pred_prob = gaussian.predict_proba(X_test)

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(accuracy_score(y_test, y_pred))

['building_windows_float_processed' 'building_windows_non_float_processed'
 'containers' 'headlamps' 'tableware' 'vehicle_windows_float_processed']
[[ 9  3  0  0  0  9]
 [10  6  1  0  0  6]
 [ 0  4  0  0  0  0]
 [ 1  0  0  8  0  0]
 [ 0  0  0  2  1  0]
 [ 2  0  0  0  1  2]]
              precision    recall  f1-score   support

           0       0.41      0.43      0.42        21
           1       0.46      0.26      0.33        23
           2       0.00      0.00      0.00         4
           3       0.80      0.89      0.84         9
           4       0.50      0.33      0.40         3
           5       0.12      0.40      0.18         5

    accuracy                           0.40        65
   macro avg       0.38      0.39      0.36        65
weighted avg       0.44      0.40      0.40        65

0.4


In [25]:
lr = LogisticRegression()
lr.fit(X_train, y_train)
y_pred = lr.predict(X_test)
y_pred_prob = lr.predict_proba(X_test)

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(accuracy_score(y_test, y_pred))

[[15  6  0  0  0  0]
 [ 8 14  0  0  1  0]
 [ 0  4  0  0  0  0]
 [ 1  0  0  8  0  0]
 [ 0  1  0  2  0  0]
 [ 2  3  0  0  0  0]]
              precision    recall  f1-score   support

           0       0.58      0.71      0.64        21
           1       0.50      0.61      0.55        23
           2       0.00      0.00      0.00         4
           3       0.80      0.89      0.84         9
           4       0.00      0.00      0.00         3
           5       0.00      0.00      0.00         5

    accuracy                           0.57        65
   macro avg       0.31      0.37      0.34        65
weighted avg       0.47      0.57      0.52        65

0.5692307692307692


C:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in l

In [26]:
print(log_loss(y_test,y_pred_prob))

1.0574757400041306
