In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.metrics import accuracy_score
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import roc_curve, roc_auc_score
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import log_loss

In [2]:
df = pd.read_csv("C:/Users/Administrator.DAI-PC2/Desktop/ML/Day1/Image_Segmentation.csv")
le = LabelEncoder()
y = le.fit_transform(df["Class"])
X = df.drop("Class", axis = 1)
print(le.classes_)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state=2021, stratify=y)

gaussian = GaussianNB()
gaussian.fit(X_train, y_train)
y_pred = gaussian.predict(X_test)
y_pred_prob = gaussian.predict_proba(X_test)

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(accuracy_score(y_test, y_pred))

['BRICKFACE' 'CEMENT' 'FOLIAGE' 'GRASS' 'PATH' 'SKY' 'WINDOW']
[[6 1 0 0 0 0 2]
 [0 7 1 0 1 0 0]
 [0 0 4 0 0 0 5]
 [0 0 0 9 0 0 0]
 [0 1 1 0 7 0 0]
 [0 0 0 0 0 9 0]
 [0 1 1 0 0 0 7]]
              precision    recall  f1-score   support

           0       1.00      0.67      0.80         9
           1       0.70      0.78      0.74         9
           2       0.57      0.44      0.50         9
           3       1.00      1.00      1.00         9
           4       0.88      0.78      0.82         9
           5       1.00      1.00      1.00         9
           6       0.50      0.78      0.61         9

    accuracy                           0.78        63
   macro avg       0.81      0.78      0.78        63
weighted avg       0.81      0.78      0.78        63

0.7777777777777778


In [3]:
print(log_loss(y_test,y_pred_prob))

3.4434736809185207


In [4]:
lr = LogisticRegression()
lr.fit(X_train, y_train)
y_pred = lr.predict(X_test)
y_pred_prob = lr.predict_proba(X_test)

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(accuracy_score(y_test, y_pred))

[[8 0 1 0 0 0 0]
 [0 7 0 0 1 0 1]
 [0 0 9 0 0 0 0]
 [0 0 0 9 0 0 0]
 [0 0 0 0 9 0 0]
 [0 0 0 0 0 9 0]
 [0 1 2 0 1 0 5]]
              precision    recall  f1-score   support

           0       1.00      0.89      0.94         9
           1       0.88      0.78      0.82         9
           2       0.75      1.00      0.86         9
           3       1.00      1.00      1.00         9
           4       0.82      1.00      0.90         9
           5       1.00      1.00      1.00         9
           6       0.83      0.56      0.67         9

    accuracy                           0.89        63
   macro avg       0.90      0.89      0.88        63
weighted avg       0.90      0.89      0.88        63

0.8888888888888888


C:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [5]:
print(log_loss(y_test,y_pred_prob))

1.055786648327205
