In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.metrics import accuracy_score
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import roc_curve, roc_auc_score
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import log_loss

In [10]:
df = pd.read_csv("C:/Users/Administrator.DAI-PC2/Desktop/ML/Day1/Glass.csv")
le = LabelEncoder()
y = le.fit_transform(df["Type"])
X = df.drop("Type", axis = 1)

print(le.classes_)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state=24, stratify=y)

gaussian = GaussianNB()
gaussian.fit(X_train, y_train)
y_pred = gaussian.predict(X_test)
y_pred_prob = gaussian.predict_proba(X_test)

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(accuracy_score(y_test, y_pred))

['building_windows_float_processed' 'building_windows_non_float_processed'
 'containers' 'headlamps' 'tableware' 'vehicle_windows_float_processed']
[[ 0  2  0  0  0 19]
 [ 2  2  1  0  0 18]
 [ 0  1  2  1  0  0]
 [ 0  0  0  8  0  1]
 [ 0  0  0  0  3  0]
 [ 0  1  0  0  0  4]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        21
           1       0.33      0.09      0.14        23
           2       0.67      0.50      0.57         4
           3       0.89      0.89      0.89         9
           4       1.00      1.00      1.00         3
           5       0.10      0.80      0.17         5

    accuracy                           0.29        65
   macro avg       0.50      0.55      0.46        65
weighted avg       0.34      0.29      0.27        65

0.2923076923076923


In [11]:
#without multiclass
lr = LogisticRegression()
lr.fit(X_train, y_train)

print(lr.coef_)
print(lr.intercept_)

y_pred = lr.predict(X_test)
y_pred_prob = lr.predict_proba(X_test)

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(accuracy_score(y_test, y_pred))

[[-1.83085700e-02 -1.07665502e+00  1.60362122e+00 -1.47933111e+00
   1.34020749e-01 -1.71275425e-01  3.76933244e-01 -3.60016370e-01
   7.50942135e-02]
 [ 2.90144981e-02 -4.10828874e-01  3.68079415e-01  5.35517215e-01
   3.92544640e-02  3.63984361e-01  2.90745578e-01  7.39449392e-02
   4.25092641e-02]
 [-5.77571663e-04 -3.84036146e-01 -9.23106734e-01  8.53037657e-01
   6.89741620e-02  6.94989579e-01  5.03001303e-02 -4.02333558e-01
   3.77226794e-02]
 [ 7.48376812e-03  4.99408436e-01 -1.43128805e+00  1.05481490e+00
   1.56903008e-02  1.31369549e-01 -7.54597921e-01  1.16443084e+00
  -7.51647516e-02]
 [-2.66519990e-02  1.12959425e+00 -7.34243351e-01 -4.27212190e-01
  -1.38230013e-01 -6.67422415e-01 -3.36724562e-01 -3.11791987e-01
  -9.29912480e-02]
 [ 9.03987442e-03  2.42517357e-01  1.11693750e+00 -5.36826469e-01
  -1.19709663e-01 -3.51645648e-01  3.73343531e-01 -1.64233866e-01
   1.28298427e-02]]
[-0.01493294  0.02041699  0.00092312  0.00466985 -0.01874829  0.00767127]
[[17  4  0  0  0  0

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in l

In [12]:
#with multiclass
lr = LogisticRegression(multi_class='ovr')
lr.fit(X_train, y_train)
y_pred = lr.predict(X_test)
y_pred_prob = lr.predict_proba(X_test)

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(accuracy_score(y_test, y_pred))

[[19  2  0  0  0  0]
 [13 10  0  0  0  0]
 [ 0  2  1  1  0  0]
 [ 1  0  0  8  0  0]
 [ 0  0  0  3  0  0]
 [ 4  1  0  0  0  0]]
              precision    recall  f1-score   support

           0       0.51      0.90      0.66        21
           1       0.67      0.43      0.53        23
           2       1.00      0.25      0.40         4
           3       0.67      0.89      0.76         9
           4       0.00      0.00      0.00         3
           5       0.00      0.00      0.00         5

    accuracy                           0.58        65
   macro avg       0.47      0.41      0.39        65
weighted avg       0.56      0.58      0.53        65

0.5846153846153846


C:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in l

In [13]:
y_probs = lr.predict_proba(X_test)


print(roc_auc_score(y_test, y_pred_prob, multi_class = 'ovr'))
print(log_loss(y_test,y_pred_prob))

0.8173553364483513
1.0343716335791842
