In [2]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.metrics import r2_score
from sklearn.model_selection import KFold
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import Ridge, Lasso, ElasticNet

In [3]:
df = pd.read_csv("C:/Users/Administrator.DAI-PC2/Desktop/ML/Day 5/Concrete_Data.csv")

y = df['Strength']
X = df.drop('Strength', axis = 1)

In [4]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state=24)

poly = PolynomialFeatures(degree =1)
lr = LinearRegression()

kfold = KFold(n_splits = 5, shuffle = True, random_state=24)


pipe = Pipeline([('POLY', poly), ('LR', lr)])
pipe.fit(X_train, y_train)
y_pred = pipe.predict(X_test)

result = cross_val_score(pipe, X, y, cv = kfold)
print(result)
print(result.mean())

[0.54197748 0.62408005 0.63130419 0.59888932 0.63678175]
0.6066065590942401


In [9]:
#ridge
ridge = Ridge()
poly = PolynomialFeatures()
pipe = Pipeline([('POLY', poly), ('LR', ridge)])
print(pipe.get_params())
params = {'POLY__degree': [1, 2, 3],
          'LR__alpha':np.linspace(0.001, 5,10)}
gcv_ridge = GridSearchCV(pipe, param_grid = params, cv = kfold)
gcv_ridge.fit(X, y)
print(gcv_ridge.best_score_)
print(gcv_ridge.best_params_)

{'memory': None, 'steps': [('POLY', PolynomialFeatures()), ('LR', Ridge())], 'verbose': False, 'POLY': PolynomialFeatures(), 'LR': Ridge(), 'POLY__degree': 2, 'POLY__include_bias': True, 'POLY__interaction_only': False, 'POLY__order': 'C', 'LR__alpha': 1.0, 'LR__copy_X': True, 'LR__fit_intercept': True, 'LR__max_iter': None, 'LR__positive': False, 'LR__random_state': None, 'LR__solver': 'auto', 'LR__tol': 0.0001}


C:\Users\Administrator.DAI-PC2\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_ridge.py:204: LinAlgWarning: Ill-conditioned matrix (rcond=2.34586e-17): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
C:\Users\Administrator.DAI-PC2\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_ridge.py:204: LinAlgWarning: Ill-conditioned matrix (rcond=2.35012e-17): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
C:\Users\Administrator.DAI-PC2\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_ridge.py:204: LinAlgWarning: Ill-conditioned matrix (rcond=2.24947e-17): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
C:\Users\Administrator.DAI-PC2\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_ridge.py:204: LinAlgWarning: Ill-conditioned matrix (rcond=2.31441e-17): result may not be accurate.
 

0.8618588992580418
{'LR__alpha': 5.0, 'POLY__degree': 3}


C:\Users\Administrator.DAI-PC2\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_ridge.py:204: LinAlgWarning: Ill-conditioned matrix (rcond=4.37437e-20): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
C:\Users\Administrator.DAI-PC2\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_ridge.py:204: LinAlgWarning: Ill-conditioned matrix (rcond=4.46494e-20): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
C:\Users\Administrator.DAI-PC2\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_ridge.py:204: LinAlgWarning: Ill-conditioned matrix (rcond=4.2311e-20): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T
C:\Users\Administrator.DAI-PC2\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_ridge.py:204: LinAlgWarning: Ill-conditioned matrix (rcond=4.38675e-20): result may not be accurate.
  

In [10]:
#lasso
lasso = Lasso()
poly = PolynomialFeatures()
pipe = Pipeline([('POLY', poly), ('LR', lasso)])
print(pipe.get_params())
params = {'POLY__degree': [1, 2, 3],
          'LR__alpha':np.linspace(0.001, 5,10)}
gcv_lasso = GridSearchCV(pipe, param_grid = params, cv = kfold)
gcv_lasso.fit(X, y)
print(gcv_lasso.best_score_)
print(gcv_lasso.best_params_)

{'memory': None, 'steps': [('POLY', PolynomialFeatures()), ('LR', Lasso())], 'verbose': False, 'POLY': PolynomialFeatures(), 'LR': Lasso(), 'POLY__degree': 2, 'POLY__include_bias': True, 'POLY__interaction_only': False, 'POLY__order': 'C', 'LR__alpha': 1.0, 'LR__copy_X': True, 'LR__fit_intercept': True, 'LR__max_iter': 1000, 'LR__positive': False, 'LR__precompute': False, 'LR__random_state': None, 'LR__selection': 'cyclic', 'LR__tol': 0.0001, 'LR__warm_start': False}


C:\Users\Administrator.DAI-PC2\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_coordinate_descent.py:678: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.335e+04, tolerance: 2.350e+01
  model = cd_fast.enet_coordinate_descent(
C:\Users\Administrator.DAI-PC2\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_coordinate_descent.py:678: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.281e+04, tolerance: 2.329e+01
  model = cd_fast.enet_coordinate_descent(
C:\Users\Administrator.DAI-PC2\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_coordinate_descent.py:678: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations

0.8526437598479252
{'LR__alpha': 0.001, 'POLY__degree': 3}


C:\Users\Administrator.DAI-PC2\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_coordinate_descent.py:678: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.597e+04, tolerance: 2.872e+01
  model = cd_fast.enet_coordinate_descent(


In [11]:
#elasticnet
elastic = ElasticNet()
poly = PolynomialFeatures()
pipe = Pipeline([('POLY', poly), ('LR', elastic)])
print(pipe.get_params())
params = {'POLY__degree': [1, 2, 3],
          'LR__alpha':np.linspace(0.001, 5,10),
         'LR__l1_ratio':np.linspace(0, 1,5)}
gcv_elasticnet = GridSearchCV(pipe, param_grid = params, cv = kfold)
gcv_elasticnet.fit(X, y)
print(gcv_elasticnet.best_score_)
print(gcv_elasticnet.best_params_)

{'memory': None, 'steps': [('POLY', PolynomialFeatures()), ('LR', ElasticNet())], 'verbose': False, 'POLY': PolynomialFeatures(), 'LR': ElasticNet(), 'POLY__degree': 2, 'POLY__include_bias': True, 'POLY__interaction_only': False, 'POLY__order': 'C', 'LR__alpha': 1.0, 'LR__copy_X': True, 'LR__fit_intercept': True, 'LR__l1_ratio': 0.5, 'LR__max_iter': 1000, 'LR__positive': False, 'LR__precompute': False, 'LR__random_state': None, 'LR__selection': 'cyclic', 'LR__tol': 0.0001, 'LR__warm_start': False}


C:\Users\Administrator.DAI-PC2\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_coordinate_descent.py:678: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.355e+04, tolerance: 2.350e+01 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
C:\Users\Administrator.DAI-PC2\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_coordinate_descent.py:678: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.506e+04, tolerance: 2.329e+01 Linear regression models with null weight for the l1 regularization term are more ef

0.852994552489777
{'LR__alpha': 0.5564444444444444, 'LR__l1_ratio': 0.25, 'POLY__degree': 3}


C:\Users\Administrator.DAI-PC2\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_coordinate_descent.py:678: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.616e+04, tolerance: 2.872e+01
  model = cd_fast.enet_coordinate_descent(


In [13]:
#inferencing
best_model = gcv_ridge.best_estimator_
best_model

Pipeline(steps=[('POLY', PolynomialFeatures(degree=3)),
                ('LR', Ridge(alpha=5.0))])

In [17]:
#unlabelled data
tst_conc = pd.read_csv("testConcrete.csv")
pred_strength = best_model.predict(tst_conc)
pred_strength

array([  63.39445435,  -37.86820406,   52.30758597, -325.36598505,
        104.60665817,  -42.1630978 , -110.17062548,  144.56471961,
        -22.42178883,  -16.64449761,   66.03425708,  238.50640923,
       -383.84854459,   90.48292861])

In [18]:
pred_strength = gcv_elasticnet.predict(tst_conc)
pred_strength

array([ 82.21156802,  71.05233914,  35.08844805,  76.84441002,
         5.26192983,   6.08289221,  63.35027459,  26.22137995,
        28.02790212, -14.5739335 ,  23.1308143 , -27.4606537 ,
        71.0008681 ,  25.22337473])

In [19]:
pred_strength = gcv_lasso.predict(tst_conc)
pred_strength

array([ 82.95994305,  70.84544084,  35.85640822,  75.18474148,
         3.16940328,   1.35863359,  59.07717154,  24.10091653,
        24.24521526, -21.73709361,  23.11744694, -31.31471995,
        67.03121838,  25.69768058])